#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local nm_file="$1"; shift
  local url_file="$1"; shift

  local pth_curl="${BASEBOX_CACHE}/curl/$(uname -s)"
  local tmp_curl="${BASEBOX_CACHE}/curl/tmp"

  mkdir -p "$pth_curl" "$tmp_curl"

  if [[ -f "$pth_curl/$nm_file" ]]; then
    return 0
  fi

  if curl -sSL -o "$tmp_curl/$nm_file.$$" "$@" "$url_file"; then
    mv -f "$tmp_curl/$nm_file.$$" "$pth_curl/$nm_file"
  else
    return $?
  fi
}

source sub "$BASH_SOURCE" "$@"
