#!/usr/bin/env bash

function main {
  local shome="${_curl_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  local nm_file="$1"; shift
  local url_file="$1"; shift

  mkdir -p "${BASEBOX_CACHE}/curl"
  if [[ -f "${BASEBOX_CACHE}/curl/$nm_file" ]]; then
    return 0
  fi

  if curl -sSL -o "${BASEBOX_CACHE}/curl/$nm_file.$$" "$@" "$url_file"; then
    mv -f "${BASEBOX_CACHE}/curl/$nm_file.$$" "${BASEBOX_CACHE}/curl/$nm_file"
  else
    return $?
  fi
}

source sub "$BASH_SOURCE" "$@"
