#!/usr/bin/env bash

function bootstrap {
  local shome="${_curl_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  pkg ensure www/curl
}

bootstrap
